import QtQuick 2.5

ListModel {
    ListElement{
        idtxtContent: "1"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "2"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_start_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "3"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_start_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "4"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_start_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "5"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_start_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "6"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_start_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "7"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_start_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "8"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "9"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "10"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "11"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "12"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "13"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "14"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "15"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "16"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "17"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
    ListElement{
        idtxtContent: "18"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }

    ListElement{
        idtxtContent: "19"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }

    ListElement{
        idtxtContent: "20"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }

    ListElement{
        idtxtContent: "21"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }

    ListElement{
        idtxtContent: "22"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }

    ListElement{
        idtxtContent: "23"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        //action1Source: "../appIMG/1.TaskScren/item_stop_all_4x.png"
        //action2Source: "../appIMG/1.TaskScren/item_edit_all_4x.png"
        //action3Source: "../appIMG/1.TaskScren/item_delete_all_4x.png"
    }
}
