import QtQuick 2.5

ListModel {
    ListElement{
        idtxtContent: "1"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "2"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "3"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "4"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "5"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "6"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "7"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "8"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "9"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "10"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "11"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "12"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "7"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "8"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "9"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "10"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "11"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
    ListElement{
        idtxtContent: "12"
        productContent: "Jordan 13 Flint Grey"
        sizeContent: "9.5"
        siteContent: "Footlocker"
        profileContent: "Privacy 3"
        proxyContent: "Private Resi"
        statusContent: "Adding to cart"
        statusColor: "#FFA94F"
        action1Source: "qrc:/image/stop_action.png"
        action2Source: "qrc:/image/edit_action.png"
        action3Source: "qrc:/image/delete_action.png"
    }
}
